const divelist = [
    {"dive": "101A", "difficulty": 1.4, "description": "Forward Dive Straight"},
    {"dive": "101B", "difficulty": 1.3, "description": "Forward Dive Pike"},
    {"dive": "101C", "difficulty": 1.2, "description": "Forward Dive Tuck"},
    {"dive": "102A", "difficulty": 1.6, "description": "Forward Somersault Straight"},
    {"dive": "102B", "difficulty": 1.5, "description": "Forward Somersault Pike"},
    {"dive": "102C", "difficulty": 1.4, "description": "Forward Somersault Tuck"},
    {"dive": "103A", "difficulty": 2.0, "description": "Forward 1-1/2 Somersault Straight"},
    {"dive": "103B", "difficulty": 1.7, "description": "Forward 1-1/2 Somersault Pike"},
    {"dive": "103C", "difficulty": 1.6, "description": "Forward 1-1/2 Somersault Tuck"},
    {"dive": "104A", "difficulty": 2.6, "description": "Forward Double Somersault Straight"},
    {"dive": "104B", "difficulty": 2.3, "description": "Forward Double Somersault Pike"},
    {"dive": "104C", "difficulty": 2.2, "description": "Forward Double Somersault Tuck"},
    {"dive": "105B", "difficulty": 2.6, "description": "Forward 2-1/2 Somersault Pike"},
    {"dive": "105C", "difficulty": 2.4, "description": "Forward 2-1/2 Somersault Tuck"},
    {"dive": "106B", "difficulty": 3.2, "description": "Forward Triple Somersault Pike"},
    {"dive": "106C", "difficulty": 2.9, "description": "Forward Triple Somersault Tuck"},
    {"dive": "107B", "difficulty": 3.3, "description": "Forward 3-1/2 Somersault Pike"},
    {"dive": "107C", "difficulty": 3.0, "description": "Forward 3-1/2 Somersault Tuck"},
    {"dive": "112B", "difficulty": 1.7, "description": "Forward Flying Somersault Pike"},
    {"dive": "112C", "difficulty": 1.6, "description": "Forward Flying Somersault Tuck"},
    {"dive": "113B", "difficulty": 1.9, "description": "Forward Flying 1-1/2 Somersault Pike"},
    {"dive": "113C", "difficulty": 1.8, "description": "Forward Flying 1-1/2 Somersault Tuck"},
    {"dive": "201A", "difficulty": 1.7, "description": "Back Dive Straight"},
    {"dive": "201B", "difficulty": 1.6, "description": "Back Dive Pike"},
    {"dive": "201C", "difficulty": 1.5, "description": "Back Dive Tuck"},
    {"dive": "202A", "difficulty": 1.7, "description": "Back Somersault Straight"},
    {"dive": "202B", "difficulty": 1.6, "description": "Back Somersault Pike"},
    {"dive": "202C", "difficulty": 1.5, "description": "Back Somersault Tuck"},
    {"dive": "203A", "difficulty": 2.5, "description": "Back 1-1/2 Somersault Straight"},
    {"dive": "203B", "difficulty": 2.3, "description": "Back 1-1/2 Somersault Pike"},
    {"dive": "203C", "difficulty": 2.0, "description": "Back 1-1/2 Somersault Tuck"},
    {"dive": "204B", "difficulty": 2.5, "description": "Back Double Somersault Pike"},
    {"dive": "204C", "difficulty": 2.2, "description": "Back Double Somersault Tuck"},
    {"dive": "205B", "difficulty": 3.2, "description": "Back 2-1/2 Somersault Pike"},
    {"dive": "205C", "difficulty": 3.0, "description": "Back 2-1/2 Somersault Tuck"},
    {"dive": "206B", "difficulty": 3.2, "description": "Back 3 Somersault Pike"},
    {"dive": "206C", "difficulty": 2.9, "description": "Back 3 Somersault Tuck"},
    {"dive": "301A", "difficulty": 1.8, "description": "Reverse Dive Straight"},
    {"dive": "301B", "difficulty": 1.7, "description": "Reverse Dive Pike"},
    {"dive": "301C", "difficulty": 1.6, "description": "Reverse Dive Tuck"},
    {"dive": "302A", "difficulty": 1.8, "description": "Reverse Somersault Straight"},
    {"dive": "302B", "difficulty": 1.7, "description": "Reverse Somersault Pike"},
    {"dive": "302C", "difficulty": 1.6, "description": "Reverse Somersault Tuck"},
    {"dive": "303A", "difficulty": 2.7, "description": "Reverse 1-1/2 Somersault Straight"},
    {"dive": "303B", "difficulty": 2.4, "description": "Reverse 1-1/2 Somersault Pike"},
    {"dive": "303C", "difficulty": 2.1, "description": "Reverse 1-1/2 Somersault Tuck"},
    {"dive": "304A", "difficulty": 2.9, "description": "Reverse Double Somersault Straight"},
    {"dive": "304B", "difficulty": 2.6, "description": "Reverse Double Somersault Pike"},
    {"dive": "304C", "difficulty": 2.3, "description": "Reverse Double Somersault Tuck"},
    {"dive": "305B", "difficulty": 3.2, "description": "Reverse 2-1/2 Somersault Pike"},
    {"dive": "305C", "difficulty": 3.0, "description": "Reverse 2-1/2 Somersault Tuck"},
    {"dive": "306B", "difficulty": 3.3, "description": "Reverse 3 Somersault Pike"},
    {"dive": "306C", "difficulty": 3.0, "description": "Reverse 3 Somersault Tuck"},
    {"dive": "312B", "difficulty": 1.8, "description": "Reverse Flying Somersault Pike"},
    {"dive": "312C", "difficulty": 1.7, "description": "Reverse Flying Somersault Tuck"},
    {"dive": "313B", "difficulty": 2.6, "description": "Reverse Flying 1-1/2 Somersault Pike"},
    {"dive": "313C", "difficulty": 2.3, "description": "Reverse Flying 1-1/2 Somersault Tuck"},
    {"dive": "401A", "difficulty": 1.8, "description": "Inward Dive Straight"},
    {"dive": "401B", "difficulty": 1.5, "description": "Inward Dive Pike"},
    {"dive": "401C", "difficulty": 1.4, "description": "Inward Dive Tuck"},
    {"dive": "402A", "difficulty": 2.0, "description": "Inward Somersault Straight"},
    {"dive": "402B", "difficulty": 1.7, "description": "Inward Somersault Pike"},
    {"dive": "402C", "difficulty": 1.6, "description": "Inward Somersault Tuck"},
    {"dive": "403B", "difficulty": 2.4, "description": "Inward 1-1/2 Somersault Pike"},
    {"dive": "403C", "difficulty": 2.2, "description": "Inward 1-1/2 Somersault Tuck"},
    {"dive": "404B", "difficulty": 3.0, "description": "Inward Double Somersault Pike"},
    {"dive": "404C", "difficulty": 2.8, "description": "Inward Double Somersault Tuck"},
    {"dive": "405B", "difficulty": 3.4, "description": "Inward 2-1/2 Somersault Pike"},
    {"dive": "405C", "difficulty": 3.1, "description": "Inward 2-1/2 Somersault Tuck"},
    {"dive": "412B", "difficulty": 2.1, "description": "Inward Flying Somersault Pike"},
    {"dive": "412C", "difficulty": 2.0, "description": "Inward Flying Somersault Tuck"},
    {"dive": "413B", "difficulty": 2.9, "description": "Inward Flying 1-1/2 Somersault Pike"},
    {"dive": "413C", "difficulty": 2.7, "description": "Inward Flying 1-1/2 Somersault Tuck"},
    {"dive": "5111A", "difficulty": 1.8, "description": "Forward Dive 1/2 Twist Straight"},
    {"dive": "5111B", "difficulty": 1.7, "description": "Forward Dive 1/2 Twist Pike"},
    {"dive": "5111C", "difficulty": 1.6, "description": "Forward Dive 1/2 Twist Tuck"},
    {"dive": "5112A", "difficulty": 2.0, "description": "Forward Dive 1 Twist Straight"},
    {"dive": "5112B", "difficulty": 1.9, "description": "Forward Dive 1 Twist Pike"},
    {"dive": "5121D", "difficulty": 1.7, "description": "Forward Som. 1/2 Twist Free"},
    {"dive": "5122D", "difficulty": 1.9, "description": "Forward Som. 1 Twist Free"},
    {"dive": "5124D", "difficulty": 2.3, "description": "Forward Som. 2 Twists Free"},
    {"dive": "5126D", "difficulty": 2.8, "description": "Forward Som. 3 Twists Free"},
    {"dive": "5131D", "difficulty": 2.0, "description": "Forward 1-1/2 Som. 1/2 Twist Free"},
    {"dive": "5132D", "difficulty": 2.2, "description": "Forward 1-1/2 Som. 1 Twist Free"},
    {"dive": "5134D", "difficulty": 2.6, "description": "Forward 1-1/2 Som. 2 Twists Free"},
    {"dive": "5136D", "difficulty": 3.1, "description": "Forward 1-1/2 Som. 3 Twists Free"},
    {"dive": "5138D", "difficulty": 3.5, "description": "Forward 1-1/2 Som. 4 Twist Free"},
    {"dive": "5151B", "difficulty": 3.0, "description": "Forward 2-1/2 Som. 1/2 Twist Pike"},
    {"dive": "5151C", "difficulty": 2.8, "description": "Forward 2-1/2 Som. 1/2 Twist Tuck"},
    {"dive": "5152B", "difficulty": 3.2, "description": "Forward 2-1/2 Som. 1 Twist Pike"},
    {"dive": "5152C", "difficulty": 3.0, "description": "Forward 2-1/2 Som. 1 Twist Tuck"},
    {"dive": "5154B", "difficulty": 3.6, "description": "Forward 2-1/2 Som. 2 Twist Pike"},
    {"dive": "5154C", "difficulty": 3.4, "description": "Forward 2-1/2 Som. 2 Twist Tuck"},
    {"dive": "5211A", "difficulty": 1.8, "description": "Back Dive 1/2 Twist Straight"},
    {"dive": "5211B", "difficulty": 1.7, "description": "Back Dive 1/2 Twist Pike"},
    {"dive": "5211C", "difficulty": 1.6, "description": "Back Dive 1/2 Twist Tuck"},
    {"dive": "5212A", "difficulty": 2.0, "description": "Back Dive 1 Twist Straight"},
    {"dive": "5221D", "difficulty": 1.7, "description": "Back Som. 1/2 Twist Free"},
    {"dive": "5222D", "difficulty": 1.9, "description": "Back Som. 1 Twist Free"},
    {"dive": "5223D", "difficulty": 2.3, "description": "Back Som. 1-1/2 Twists Free"},
    {"dive": "5225D", "difficulty": 2.7, "description": "Back Som. 2-1/2 Twists Free"},
    {"dive": "5227D", "difficulty": 3.2, "description": "Back Som. 3-1/2 Twists Free"},
    {"dive": "5231D", "difficulty": 2.1, "description": "Back 1-1/2 Som. 1/2 Twist Free"},
    {"dive": "5233D", "difficulty": 2.5, "description": "Back 1-1/2 Som. 1-1/2 Twists Free"},
    {"dive": "5235D", "difficulty": 2.9, "description": "Back 1-1/2 Som. 2-1/2 Twists Free"},
    {"dive": "5251B", "difficulty": 2.9, "description": "Back 2-1/2 Som. 1/2 Twist Pike"},
    {"dive": "5251C", "difficulty": 2.7, "description": "Back 2-1/2 Som. 1/2 Twist Tuck"},
    {"dive": "5311A", "difficulty": 1.9, "description": "Reverse Dive 1/2 Twist Straight"},
    {"dive": "5311B", "difficulty": 1.8, "description": "Reverse Dive 1/2 Twist Pike"},
    {"dive": "5311C", "difficulty": 1.7, "description": "Reverse Dive 1/2 Twist Tuck"},
    {"dive": "5312A", "difficulty": 2.1, "description": "Reverse Dive 1 Twist Straight"},
    {"dive": "5321D", "difficulty": 1.8, "description": "Reverse Som. 1/2 Twist Free"},
    {"dive": "5322D", "difficulty": 2.0, "description": "Reverse Som. 1 Twist Free"},
    {"dive": "5323D", "difficulty": 2.4, "description": "Reverse Som. 1-1/2 Twists Free"},
    {"dive": "5325D", "difficulty": 2.8, "description": "Reverse Som. 2-1/2 Twists Free"},
    {"dive": "5331D", "difficulty": 2.2, "description": "Reverse 1-1/2 Som. 1/2 Twist Free"},
    {"dive": "5333D", "difficulty": 2.6, "description": "Reverse 1-1/2 Som. 1-1/2 Twists Free"},
    {"dive": "5335D", "difficulty": 3.0, "description": "Reverse 1-1/2 Som. 2-1/2 Twists Free"},
    {"dive": "5351B", "difficulty": 2.9, "description": "Reverse 2-1/2 Som. 1/2 Twists Pike"},
    {"dive": "5351C", "difficulty": 2.7, "description": "Reverse 2-1/2 Som. 1/2 Twists Tuck"},
    {"dive": "5353B", "difficulty": 3.5, "description": "Reverse 2-1/2 Som. 1-1/2 Twists Pike"},
    {"dive": "5353C", "difficulty": 3.3, "description": "Reverse 2-1/2 Som. 1-1/2 Twists Tuck"},
    {"dive": "5355B", "difficulty": 3.9, "description": "Reverse 2-1/2 Som. 2-1/2 Twists Pike"},
    {"dive": "5355C", "difficulty": 3.7, "description": "Reverse 2-1/2 Som. 2-1/2 Twists Tuck"},
    {"dive": "5411A", "difficulty": 2.0, "description": "Inward Dive 1/2 Twist Straight"},
    {"dive": "5411B", "difficulty": 1.7, "description": "Inward Dive 1/2 Twist Pike"},
    {"dive": "5411C", "difficulty": 1.6, "description": "Inward Dive 1/2 Twist Tuck"},
    {"dive": "5412A", "difficulty": 2.2, "description": "Inward Dive 1 Twist Straight"},
    {"dive": "5412B", "difficulty": 1.9, "description": "Inward Dive 1 Twist Pike"},
    {"dive": "5412C", "difficulty": 1.8, "description": "Inward Dive 1 Twist Tuck"},
    {"dive": "5421D", "difficulty": 1.9, "description": "Inward Som. 1/2 Twist Free"},
    {"dive": "5422D", "difficulty": 2.1, "description": "Inward Som. 1 Twist Free"},
    {"dive": "5432D", "difficulty": 2.7, "description": "Inward 1-1/2 Som. 1 Twist Free"},
    {"dive": "5434D", "difficulty": 3.1, "description": "Inward 1-1/2 Som. 2 Twists Free"},
]

export default divelist;