export const boysMeetArray2324 = [
    {meet: "Conference Relay", location: "Maple Grove MS", date: "12/9/23"},
    {meet: "Andover vs Irondale", location: "Edgewood MS", date: "12/12/23"},
    {meet: "Andover vs Coon Rapids", location: "Fred Moore MS", date: "12/14/23"},
    {meet: "Bengal Invite", location: "Northdale MS", date: "12/16/23"},
    {meet: "Alumni Meet", location: "Fred Moore", date: "12/27/23"},
    {meet: "Andover vs Centennial", location: "Centennial HS", date: "1/4/24"},
    {meet: "Fargo Invite", location: "Hulbert Aquatic Center", date: "1/6/24"},
    {meet: "Andover vs Champlin Park", location: "Jackson MS", date: "1/11/24"},
    {meet: "True Team Sections", location: "Northdale MS", date: "1/13/24"},
    {meet: "Andover vs White Bear Lake", location: "Fred Moore", date: "1/16/24"},
    {meet: "Andover vs Maple Grove", location: "Maple Grove MS", date: "1/18/24"},
    {meet: "True Team State", location: "Jean K Freeman Aquatic Center", date: "1/20/24"},
    {meet: "Andover vs Cambridge-Isanti", location: "Cambridge-Isanti HS", date: "1/23/24"},
    {meet: "Andover vs Park Center", location: "Fred Moore", date: "1/25/24"},
    {meet: "Tournament of Champions", location: "Fred Moore", date: "2/1/24"},
    {meet: "7AA Section Diving Prelim", location: "Northdale MS", date: "2/23/24"},
    {meet: "State Diving Prelims", location: "Jean K Freeman Aquatic Center", date: "2/29/24"},
    {meet: "State Diving Finals", location: "Jean K Freeman Aquatic Center", date: "3/2/24"},
];

export const girlsMeetArray2324 = [
    {meet: "Conference Relay", location: "Northdale MS", date: "8/24/23"},
    {meet: "Andover vs Blaine", location: "Northdale MS", date: "8/29/23"},
    {meet: "Andover vs Maple Grove", location: "Maple Grove MS", date: "8/31/23"},
    {meet: "Andover vs Armstrong", location: "Fred Moore", date: "9/7/23"},
    {meet: "Bengal Invite", location: "Northdale MS", date: "9/9/23"},
    {meet: "Andover vs Anoka", location: "Fred Moore", date: "9/14/23"},
    {meet: "Fargo Invite", location: "Hulbert Aquatic Center", date: "9/16/23"},
    {meet: "Anoka vs Rogers", location: "VandenBerge MS", date: "9/21/23"},
    {meet: "Maroon and Gold Invite", location: "Jean K Freeman Aquatic Center", date: "9/23/23"},
    {meet: "Andover vs Elk River", location: "Fred Moore", date: "9/28/23"},
    {meet: "Andover vs Coon Rapids", location: "Fred Moore", date: "10/10/23"},
    {meet: "True Team", location: "Northdale MS", date: "10/14/23"},
    {meet: "Tournament of Champions", location: "TBD", date: "10/17/23"},
    {meet: "True Team State", location: "Jean K Freeman Aquatic Center", date: "10/21/23"},
    {meet: "JV Championship", location: "Northdale MS", date: "10/28/23"},
    {meet: "7AA Section Diving Prelim", location: "Northdale MS", date: "11/10/23"},
    {meet: "7AA Section Diving Finals", location: "Northdale MS", date: "11/11/23"},
    {meet: "State Diving Prelims", location: "Jean K Freeman Aquatic Center", date: "11/16/23"},
    {meet: "State Diving Finals", location: "Jean K Freeman Aquatic Center", date: "11/18/23"}
];